
    <meta charset="utf-8" />
    <link rel="stylesheet" type="text/css" href="estilo.css" title="Estilo principal">
    <link rel="stylesheet" href="css/fontello.css">
    <link rel="alternate stylesheet" href="contraste.css" title="Modo alto contraste">
    <link rel="alternate stylesheet" href="letragrande.css" title="Modo letras grandes">
    <link rel="alternate stylesheet" href="contrasteyletra.css" title="Alto contraste y letras grandes">
    <title><?php echo $title; ?></title>
