<body>
<h2>Últimas fotos</h2>
	<div id="cajas">
		<div>
			<img src="imagenes/imagen1.jpg" alt="imagen2">
			<p><span class="icon-pencil"></span><strong>Título</strong> : Atardecer</p>
			<p><span class="icon-calendar-empty"></span><strong>Fecha</strong> : 27-9-2020</p>
			<p><span class="icon-eyedropper"></span><strong>País</strong> : España</p>
		</div>
		<div>
			<img src="imagenes/imagen1.jpg" alt="imagen2">
			<p><span class="icon-pencil"></span><strong>Título</strong> : Atardecer</p>
			<p><span class="icon-calendar-empty"></span><strong>Fecha</strong> : 27-9-2020</p>
			<p><span class="icon-eyedropper"></span><strong>País</strong> : España</p>
		</div>
		<div>
			<img src="imagenes/imagen1.jpg" alt="imagen2">
			<p><span class="icon-pencil"></span><strong>Título</strong> : Atardecer</p>
			<p><span class="icon-calendar-empty"></span><strong>Fecha</strong> : 27-9-2020</p>
			<p><span class="icon-eyedropper"></span><strong>País</strong> : España</p>
		</div>
		<div>
			<img src="imagenes/imagen1.jpg" alt="imagen2">
			<p><span class="icon-pencil"></span><strong>Título</strong> : Atardecer</p>
			<p><span class="icon-calendar-empty"></span><strong>Fecha</strong> : 27-9-2020</p>
			<p><span class="icon-eyedropper"></span><strong>País</strong> : España</p>
		</div>
		<div>
			<img src="imagenes/imagen1.jpg" alt="imagen2">
			<p><span class="icon-pencil"></span><strong>Título</strong> : Atardecer</p>
			<p><span class="icon-calendar-empty"></span><strong>Fecha</strong> : 27-9-2020</p>
			<p><span class="icon-eyedropper"></span><strong>País</strong> : España</p>
		</div>
	</div>
</body>